### ISSUE TITLE
如何进行自己的训练呢？比如瑜伽姿势识别？

### ISSUE THREAD

**Issue by genggeng1104** [wfnian/posture_recognition#16]
大佬，救命啊！！！我的毕设也和深度学习有关（然而我根本不会-.-），想请教一下怎么训练自己的模型。
您的项目我已经跑起来了

**Comment by wfnian** [comment]
其实就是三个步骤

1. 采集数据并做好分类
2. 训练模型
3. 使用模型进行预测
瑜伽的话类似这个分类，你只需要将采集的数据分好类别，然后将代码里面所有23分类改成对应的类别，然后进行训练就行，不难，就是工作量有点多，手动狗头。最难的是我明天早上的英语口语考试，我还没背。:octocat:

**Comment by genggeng1104** [comment]
好的，感谢及时回复。哈哈哈，祝你明天英语口语考试顺利过过过！

**Comment by genggeng1104** [comment]
好的，感谢及时回复。哈哈哈，祝你明天英语口语考试顺利过过过！
